/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef timeRPC_CONSTANTS_H
#define timeRPC_CONSTANTS_H

#include "timeRPC_types.h"



class timeRPCConstants {
 public:
  timeRPCConstants();

};

extern const timeRPCConstants g_timeRPC_constants;



#endif
